swagger: '2.0'
info:
  title: Тестовое задание
  description: API для работы с учениками, занятиями и оценками
  version: 1.0.0
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /users:
    get:
      summary: Получить список учеников
      responses:
        200:
          description: Успешный запрос
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
    post:
      summary: Добавить одного ученика
      parameters:
        - name: user
          in: body
          description: Данные нового ученика
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        200:
          description: Успешное добавление
          schema:
            $ref: '#/definitions/User'

  /lessons/{id}:
    get:
      summary: Получить информацию о занятии по ID
      parameters:
        - name: id
          in: path
          description: ID занятия
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Успешный запрос
          schema:
            $ref: '#/definitions/Lesson'

  /lessons:
    post:
      summary: Добавить занятие
      parameters:
        - name: lesson
          in: body
          description: Данные нового занятия
          required: true
          schema:
            $ref: '#/definitions/Lesson'
      responses:
        200:
          description: Успешное добавление
          schema:
            $ref: '#/definitions/Lesson'

  /lessons/{id}/evaluations:
    post:
      summary: Добавить оценку ученика по занятию
      parameters:
        - name: id
          in: path
          description: ID занятия
          required: true
          type: integer
          format: int64
        - name: evaluation
          in: body
          description: Данные новой оценки
          required: true
          schema:
            $ref: '#/definitions/Evaluation'
      responses:
        200:
          description: Успешное добавление
          schema:
            $ref: '#/definitions/Evaluation'

definitions:
  User:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      age:
        type: integer

  Lesson:
    type: object
    properties:
      id:
        type: integer
      subject:
        type: string
      date:
        type: string
        format: date-time

  Evaluation:
    type: object
    properties:
      id:
        type: number
      userId:
        type: integer
      lessonId:
        type: integer
      grade:
        type: integer
        minimum: 1
        maximum: 5
